project:
  type: website
  resources:
    - "images/twitter-card.png"
  render:
    - "*.qmd"
    - "!materials/exercises"

website:
  page-navigation: true
  title: "Graphic Design with ggplot2"
  description: "Homepage for rstudio::conf(2022) workshop"
  site-url: "https://rstudio-conf-2022.github.io/ggplot2-graphic-design/"
  
  repo-url: https://github.com/rstudio-conf-2022/ggplot2-graphic-design
  repo-actions: [edit, issue]

  opengraph: true
  twitter-card:
    creator: "@CedScherer"
    image: "/images/twitter-card.png"

  page-footer:
    left: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    right: "&copy; Copyright 2022, Cédric Scherer and Marco Sciaini"
    background: "#FFEDC2"

  navbar:
    background: "#FFEDC2"
    logo: "images/ggplot2.png"
    pinned: true
    align: center
    right:
      - icon: bulb
        text: Sessions
        menu: 
          - text: Introduction
            href: modules/d1-01_introduction.qmd
          - text: Concepts of ggplot2 Pt. 1
            href: modules/d1-02_concepts_pt1.qmd
          - text: Concepts of ggplot2 Pt. 2
            href: modules/d1-05_concepts_pt2.qmd
          - text: Data Communication
            href: modules/d1-10_data_com.qmd
          - text: Working with Annotations & Labels
            href: modules/d2-01_lab_ann.qmd
          - text: Working with Colors
            href: modules/d2-03_colors.qmd
          - text: Working with Layouts & Compostion
            href: modules/d2-05_layout.qmd
          - text: Group Project
            href: modules/d2-07_project.qmd
      - icon: font
        href: course_fonts.zip
        text: Fonts
      - icon: github
        href: https://github.com/rstudio-conf-2022/ggplot2-graphic-design
        text: GitHub
      #- icon: cloud-fill
      #  href: https://rstudio.cloud/spaces/235465
      #  text: RStudio Cloud+
    left:
     - href: index.qmd
       text: Home
     - href: schedule.qmd
     - href: license.qmd

format:
  html:
    theme:
      light: [cosmo, theme.scss]
    toc: true
    code-copy: true
    code-overflow: wrap
    mainfont: "Cabinet Grotesk"

