project:
  type: website
  resources:
    - "images/twitter-card.png"

website:
  page-navigation: true
  title: "Graphic Design with ggplot2"
  description: "Homepage for rstudio::conf(2022) workshop"
  site-url: "https://rstudio-conf-2022.github.io/ggplot2-graphic-design/"
  
  repo-url: https://github.com/rstudio-conf-2022/ggplot2-graphic-design
  repo-actions: [edit, issue]

  opengraph: true
  twitter-card:
    creator: "@CedScherer"
    image: "/images/twitter-card.png"

  page-footer:
    left: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    right: "&copy; Copyright 2022, Cédric Scherer and Marco Sciaini"
    background: "#606060"

  navbar:
    background: "#606060"
    logo: "images/ggplot2.png"
    pinned: true
    align: center
    right:
      - icon: github
        href: https://github.com/rstudio-conf-2022/ggplot2-graphic-design
        text: GitHub
      - icon: cloud-fill
        href: https://rstudio.cloud/spaces/xxx
        text: RStudio Cloud+
    left:
     - href: index.qmd
       text: Home
     - href: schedule.qmd
     - href: team.qmd
     - href: resources.qmd
     - href: license.qmd

format:
  html:
    theme:
      light: [cosmo, theme.scss]
      dark: [cosmo, theme-dark.scss]
    toc: true
    code-copy: true
    code-overflow: wrap
    mainfont: "Atkinson Hyperlegible"

editor: visual

