project:
  type: website
  resources:
    - "images/twitter-card.png"
  render:
    - "*.qmd"
    - "!materials/exercises"

website:
  page-navigation: true
  title: "Graphic Design with ggplot2"
  description: "Homepage for rstudio::conf(2022) workshop"
  site-url: "https://rstudio-conf-2022.github.io/ggplot2-graphic-design/"
  
  repo-url: https://github.com/rstudio-conf-2022/ggplot2-graphic-design
  repo-actions: [edit, issue]

  opengraph: true
  twitter-card:
    creator: "@CedScherer"
    image: "/images/twitter-card.png"

  page-footer:
    left: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    right: "&copy; Copyright 2022, Cédric Scherer and Marco Sciaini"
    background: "#FFEDC2"

  navbar:
    background: "#FFEDC2"
    logo: "images/ggplot2.png"
    pinned: true
    align: center
    right:
      - icon: bulb
        text: Solutions
        menu: 
          - text: 02_concepts_pt1_ex1_solution
            href: materials/solutions/02_concepts_pt1_ex1_solution.qmd
          - text: 02_concepts_pt1_ex2_solution
            href: materials/solutions/02_concepts_pt1_ex2_solution.qmd
          - text: 03_concepts_pt2_ex1_solution
            href: materials/solutions/03_concepts_pt2_ex1_solution.qmd
          - text: 03_concepts_pt2_ex2_solution
            href: materials/solutions/03_concepts_pt2_ex2_solution.qmd
          - text: 04_data_communication_ex1_solution
            href: materials/solutions/04_data_communication_ex1_solution.pdf
          - text: 05_annotations_ex1_solution
            href: materials/solutions/05_annotations_ex1_solution.qmd
          - text: 05_annotations_ex2_solution
            href: materials/solutions/05_annotations_ex2_solution.qmd
          - text: 06_colors_ex1_solution
            href: materials/solutions/06_colors_ex1_solution.qmd
          - text: 08_group_projects_solutions
            href: materials/solutions/08_group_projects_solutions.qmd
      - icon: font
        href: course_fonts.zip
        text: Fonts
      - icon: github
        href: https://github.com/rstudio-conf-2022/ggplot2-graphic-design
        text: GitHub
      - icon: cloud-fill
        href: https://rstudio.cloud/spaces/235465
        text: RStudio Cloud+
    left:
     - href: index.qmd
       text: Home
     - href: schedule.qmd
     - href: license.qmd

format:
  html:
    theme:
      light: [cosmo, theme.scss]
    toc: true
    code-copy: true
    code-overflow: wrap
    mainfont: "Cabinet Grotesk"

